name = "Steel of the Nether"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38f6fa226161615ccd1783dbacb82b8f84245e818e7e6135270844fadc4337c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
