name = "Steel of the Nether"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c1acffbdcf1e9cc1067aa2082f81c68b641a7da5afc5c6afdd61f9dbf01dd49"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
