#Ledger mod config
#Mon Sep 21 11:03:06 PDT 2026
blocksPerTick=20
containerBlacklist=sophisticatedbackpacks
logRetentionDays=90
maxSearchRadius=500
pageSize=5
progressIntervalTicks=40
queryTimeoutSeconds=20
spawnLinkRadius=6
spawnLinkWindowSeconds=3
trackBookEdits=true
trackContainerBreakItems=true
trackContainerItems=true
trackContainers=true
trackDispensers=true
trackEntityKills=true
trackEntitySpawns=true
trackExplosions=true
trackFakePlayers=true
trackFarmlandTrample=true
trackFluidSolidify=false
trackItemDrops=true
trackItemPickups=true
trackLectern=true
trackMobGriefing=true
trackMultiBlockPlace=true
trackPistons=false
trackPlayerDeaths=true
trackSignEdits=true
